// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2, arg3, arg4);
}

export function ExportPDVsCSV(arg1) {
  return window['go']['main']['App']['ExportPDVsCSV'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetExportFolders() {
  return window['go']['main']['App']['GetExportFolders']();
}

export function GetIP() {
  return window['go']['main']['App']['GetIP']();
}

export function GetLogMarkers() {
  return window['go']['main']['App']['GetLogMarkers']();
}

export function GetPDVsFromLog() {
  return window['go']['main']['App']['GetPDVsFromLog']();
}

export function GetPDVsRaw() {
  return window['go']['main']['App']['GetPDVsRaw']();
}

export function GetServiceStatuses() {
  return window['go']['main']['App']['GetServiceStatuses']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function RestartComponent(arg1) {
  return window['go']['main']['App']['RestartComponent'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
