// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {parser} from '../models';
import {config} from '../models';
import {main} from '../models';

export function CheckForUpdates():Promise<updater.UpdateResponse>;

export function ChooseFolder():Promise<string>;

export function DownloadAndInstallUpdate(arg1:string):Promise<boolean|string>;

export function ExportLogs(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<boolean|string>;

export function ExportPDVsCSV(arg1:Array<parser.PDVInfo>):Promise<boolean|string>;

export function GetExportFolders():Promise<Array<string>>;

export function GetIP():Promise<string>;

export function GetLogMarkers():Promise<Array<config.LogMarker>>;

export function GetPDVsFromLog():Promise<main.PDVResponse>;

export function GetPDVsRaw():Promise<main.PDVResponse>;

export function GetServiceStatuses():Promise<Array<main.ComponentStatus>>;

export function GetSettings():Promise<config.Settings>;

export function IsAdmin():Promise<boolean>;

export function RestartAsAdmin():Promise<void>;

export function RestartComponent(arg1:string):Promise<boolean|string>;

export function SaveSettings(arg1:config.Settings):Promise<void>;
